package com.github.mobdev778.aiadventchallenge.presentation.app

import com.github.mobdev778.aiadventchallenge.data.chat.datasource.ChatDatabaseModule
import com.github.mobdev778.aiadventchallenge.data.mcpserver.datasource.McpServerDatabaseModule
import com.github.mobdev778.aiadventchallenge.data.network.NetworkModule
import com.github.mobdev778.aiadventchallenge.data.profile.datasource.ProfileDatabaseModule
import com.github.mobdev778.aiadventchallenge.data.rag.datasource.RagDatabaseModule
import com.github.mobdev778.aiadventchallenge.data.settings.datasource.SettingsDatabaseModule
import com.github.mobdev778.aiadventchallenge.data.taskcontext.datasource.TaskContextDatabaseModule
import com.github.mobdev778.aiadventchallenge.infrastructure.logging.PluginUncaughtExceptionHandler
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.project.Project
import com.intellij.openapi.startup.ProjectActivity
import org.koin.core.context.GlobalContext
import org.koin.core.context.startKoin
import org.koin.ksp.generated.defaultModule
import org.koin.ksp.generated.module

class PluginInitializer : ProjectActivity {

    override suspend fun execute(project: Project) {
        ensureKoinStarted()
    }

    companion object {
        @Volatile
        private var started: Boolean = false

        /**
         * Toolwindows can be created before `postStartupActivity` runs.
         * This method makes DI initialization idempotent and safe to call from anywhere.
         */
        fun ensureKoinStarted() {
            if (started) return

            // Явно запрашиваем наш сервис! Это создаст инстанс PluginShutdownHandlerService,
            // запустит корутины и подпишет его на автоматический dispose при выключении.
            ApplicationManager.getApplication().getService(PluginShutdownHandlerService::class.java)

            synchronized(this) {
                if (started) return
                if (GlobalContext.getOrNull() != null) {
                    started = true
                    return
                }

                startKoin {
                    // Koin definitions generated by KSP from @Single/@Factory annotations.
                    // See build/generated/ksp/.../org/koin/ksp/generated/Default.kt
                    defaultModule()

                    modules(
                        AppModule().module,
                        NetworkModule().module,
                        ChatDatabaseModule().module,
                        SettingsDatabaseModule().module,
                        ProfileDatabaseModule().module,
                        RagDatabaseModule().module,
                        TaskContextDatabaseModule().module,
                        McpServerDatabaseModule().module,
                    )
                }

                installUncaughtExceptionHandler()
                started = true
            }
        }

        private fun installUncaughtExceptionHandler() {
            val currentHandler = Thread.getDefaultUncaughtExceptionHandler()
            if (currentHandler is PluginUncaughtExceptionHandler) return

            Thread.setDefaultUncaughtExceptionHandler(
                PluginUncaughtExceptionHandler(previousHandler = currentHandler)
            )
        }
    }
}
